syntax = "proto3";

package engine;
option go_package = "./;pb";

import "common.proto";

service EngineService {
  // Match lifecycle
  rpc InitGame(InitGameRequest) returns (InitGameResponse);
  rpc MakeMove(MakeMoveRequest) returns (MakeMoveResponse);
  rpc GetState(GetStateRequest) returns (GetStateResponse);

  // Health & registration
  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message InitGameRequest {
  string ID = 1;
  repeated string playerIDs = 2;
}

message InitGameResponse {
  string message = 1;
}

message MakeMoveRequest {
  string ID = 1;
  string playerID = 2;
  bytes movePayload = 3; // game-specific
}

message MakeMoveResponse {
  bool valid = 1;
  string message = 2;
  bool gameOver = 3;
  string nextPlayerID = 4;
}

message GetStateRequest {
  string ID = 1;
  string playerID = 2; // important for hidden info games
}

message GetStateResponse {
  bytes statePayload = 1; // game-specific
  int64  version = 2;
}