syntax = "proto3";

package smtp;
option go_package = "./;pb";

import "common.proto";


service SMTPService {
  rpc SendEmail(SendEmailRequest) returns (SendEmailResponse);

  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message SendEmailRequest {
  string email = 1;
  string gamer_tag = 2;
  string avatar_url = 3;
  string topic = 4;
}

message SendEmailResponse {
  bool success = 1;
  string err=2;
}