syntax = "proto3";

package token;
option go_package = "./;pb";

import "common.proto";

service TokenService {
  rpc GenerateToken(GenerateTokenRequest) returns (GenerateTokenResponse);
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (GenerateTokenResponse);
  
  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message GenerateTokenRequest {
  string user_id = 1;
  string gamer_tag = 2;
}

message GenerateTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  int64 expires_in = 3;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  bool valid = 1;
  string user_id = 2;
  string gamer_tag = 3;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}
