syntax = "proto3";

package user;
option go_package = "./;pb";

import "common.proto";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (UserResponse);
  rpc GetUser(GetUserRequest) returns (UserResponse);
  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message CreateUserRequest {
  string email = 1;
  string password = 2;
  string gamer_tag = 3;
  string avatar_url = 4;
}

message GetUserRequest {
  string id = 1;
}

message UserResponse {
  string id = 1;
  string email = 2;
  string gamer_tag = 3;
  string avatar_url = 4;
  string access_token = 5;
  string refresh_token = 6;
}

