syntax = "proto3";

package user;
option go_package = "./;pb";

import "common.proto";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (UserResponse);
  rpc GetUser(GetUserRequest) returns (UserResponse);
  
  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message CreateUserRequest {
  string email = 1;
  string password = 2;
  string gamerTag = 3;
  string avatarURL = 4;
}

message GetUserRequest {
  string ID = 1;
}

message UserResponse {
  string ID = 1;
  string email = 2;
  string gamerTag = 3;
  string avatarURL = 4;
  string accessToken = 5;
  string refreshToken = 6;
}

