syntax = "proto3";

package user;
option go_package = "./;pb";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (UserResponse);
  rpc GetUser(GetUserRequest) returns (UserResponse);
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse);
  rpc RegisterService(RegisterServiceRequest) returns (RegisterServiceResponse);
}

message RegisterServiceRequest {
  string service_name = 1;
  string service_port = 2;
}

message RegisterServiceResponse {
  string message = 1;
}

message HealthCheckRequest {}

message HealthCheckResponse {
  string status = 1; // "ok" or "fail"
}

message CreateUserRequest {
  string username = 1;
  string avatar_url = 2;
}

message GetUserRequest {
  string id = 1;
}

message UserResponse {
  string id = 1;
  string username = 2;
  string avatar_url = 3;
  string access_token = 4;
  string refresh_token = 5;
}
