syntax = "proto3";

package token;
option go_package = "./;pb";

import "common.proto";

service TokenService {
  rpc GenerateToken(GenerateTokenRequest) returns (GenerateTokenResponse);
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (GenerateTokenResponse);
  
  rpc HealthCheck(common.HealthCheckRequest) returns (common.HealthCheckResponse);
  rpc RegisterService(common.RegisterServiceRequest) returns (common.RegisterServiceResponse);
}

message GenerateTokenRequest {
  string userID = 1;
  string gamerTag = 2;
}

message GenerateTokenResponse {
  string accessToken = 1;
  string refreshToken = 2;
  int64 expiresIn = 3;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  bool valid = 1;
  string userID = 2;
  string gamerTag = 3;
}

message RefreshTokenRequest {
  string refreshToken = 1;
}
