// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetRequest) Reset() {
	*x = CacheSetRequest{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetRequest) ProtoMessage() {}

func (x *CacheSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetRequest.ProtoReflect.Descriptor instead.
func (*CacheSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CacheSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CacheGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetRequest) Reset() {
	*x = CacheGetRequest{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetRequest) ProtoMessage() {}

func (x *CacheGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetRequest.ProtoReflect.Descriptor instead.
func (*CacheGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDeleteRequest) Reset() {
	*x = CacheDeleteRequest{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDeleteRequest) ProtoMessage() {}

func (x *CacheDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDeleteRequest.ProtoReflect.Descriptor instead.
func (*CacheDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *CacheDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *CacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CacheResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServicePort   string                 `protobuf:"bytes,2,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "online" or "expired"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceResponse) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

func (x *GetServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{6}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*GetServiceResponse  `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{7}
}

func (x *ListServicesResponse) GetServices() []*GetServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x05cache\x1a\fcommon.proto\"Z\n" +
	"\x0fCacheSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"#\n" +
	"\x0fCacheGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x12CacheDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\rCacheResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"6\n" +
	"\x11GetServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"r\n" +
	"\x12GetServiceResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_port\x18\x02 \x01(\tR\vservicePort\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x15\n" +
	"\x13ListServicesRequest\"M\n" +
	"\x14ListServicesResponse\x125\n" +
	"\bservices\x18\x01 \x03(\v2\x19.cache.GetServiceResponseR\bservices2\xfb\x01\n" +
	"\fCacheService\x123\n" +
	"\x03Set\x12\x16.cache.CacheSetRequest\x1a\x14.cache.CacheResponse\x123\n" +
	"\x03Get\x12\x16.cache.CacheGetRequest\x1a\x14.cache.CacheResponse\x129\n" +
	"\x06Delete\x12\x19.cache.CacheDeleteRequest\x1a\x14.cache.CacheResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponse2\xf1\x01\n" +
	"\x0fRegistryService\x12R\n" +
	"\x0fRegisterService\x12\x1e.common.RegisterServiceRequest\x1a\x1f.common.RegisterServiceResponse\x12A\n" +
	"\n" +
	"GetService\x12\x18.cache.GetServiceRequest\x1a\x19.cache.GetServiceResponse\x12G\n" +
	"\fListServices\x12\x1a.cache.ListServicesRequest\x1a\x1b.cache.ListServicesResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cache_proto_goTypes = []any{
	(*CacheSetRequest)(nil),         // 0: cache.CacheSetRequest
	(*CacheGetRequest)(nil),         // 1: cache.CacheGetRequest
	(*CacheDeleteRequest)(nil),      // 2: cache.CacheDeleteRequest
	(*CacheResponse)(nil),           // 3: cache.CacheResponse
	(*GetServiceRequest)(nil),       // 4: cache.GetServiceRequest
	(*GetServiceResponse)(nil),      // 5: cache.GetServiceResponse
	(*ListServicesRequest)(nil),     // 6: cache.ListServicesRequest
	(*ListServicesResponse)(nil),    // 7: cache.ListServicesResponse
	(*HealthCheckRequest)(nil),      // 8: common.HealthCheckRequest
	(*RegisterServiceRequest)(nil),  // 9: common.RegisterServiceRequest
	(*HealthCheckResponse)(nil),     // 10: common.HealthCheckResponse
	(*RegisterServiceResponse)(nil), // 11: common.RegisterServiceResponse
}
var file_cache_proto_depIdxs = []int32{
	5,  // 0: cache.ListServicesResponse.services:type_name -> cache.GetServiceResponse
	0,  // 1: cache.CacheService.Set:input_type -> cache.CacheSetRequest
	1,  // 2: cache.CacheService.Get:input_type -> cache.CacheGetRequest
	2,  // 3: cache.CacheService.Delete:input_type -> cache.CacheDeleteRequest
	8,  // 4: cache.CacheService.HealthCheck:input_type -> common.HealthCheckRequest
	9,  // 5: cache.RegistryService.RegisterService:input_type -> common.RegisterServiceRequest
	4,  // 6: cache.RegistryService.GetService:input_type -> cache.GetServiceRequest
	6,  // 7: cache.RegistryService.ListServices:input_type -> cache.ListServicesRequest
	3,  // 8: cache.CacheService.Set:output_type -> cache.CacheResponse
	3,  // 9: cache.CacheService.Get:output_type -> cache.CacheResponse
	3,  // 10: cache.CacheService.Delete:output_type -> cache.CacheResponse
	10, // 11: cache.CacheService.HealthCheck:output_type -> common.HealthCheckResponse
	11, // 12: cache.RegistryService.RegisterService:output_type -> common.RegisterServiceResponse
	5,  // 13: cache.RegistryService.GetService:output_type -> cache.GetServiceResponse
	7,  // 14: cache.RegistryService.ListServices:output_type -> cache.ListServicesResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
