// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayerIDs     []string               `protobuf:"bytes,2,rep,name=playerIDs,proto3" json:"playerIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGameRequest) Reset() {
	*x = InitGameRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGameRequest) ProtoMessage() {}

func (x *InitGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGameRequest.ProtoReflect.Descriptor instead.
func (*InitGameRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *InitGameRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InitGameRequest) GetPlayerIDs() []string {
	if x != nil {
		return x.PlayerIDs
	}
	return nil
}

type InitGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGameResponse) Reset() {
	*x = InitGameResponse{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGameResponse) ProtoMessage() {}

func (x *InitGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGameResponse.ProtoReflect.Descriptor instead.
func (*InitGameResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *InitGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayerID      string                 `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MovePayload   []byte                 `protobuf:"bytes,3,opt,name=movePayload,proto3" json:"movePayload,omitempty"` // game-specific
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *MakeMoveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MakeMoveRequest) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *MakeMoveRequest) GetMovePayload() []byte {
	if x != nil {
		return x.MovePayload
	}
	return nil
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GameOver      bool                   `protobuf:"varint,3,opt,name=gameOver,proto3" json:"gameOver,omitempty"`
	NextPlayerID  string                 `protobuf:"bytes,4,opt,name=nextPlayerID,proto3" json:"nextPlayerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *MakeMoveResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *MakeMoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MakeMoveResponse) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *MakeMoveResponse) GetNextPlayerID() string {
	if x != nil {
		return x.NextPlayerID
	}
	return ""
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayerID      string                 `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"` // important for hidden info games
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetStateRequest) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatePayload  []byte                 `protobuf:"bytes,1,opt,name=statePayload,proto3" json:"statePayload,omitempty"` // game-specific
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GetStateResponse) GetStatePayload() []byte {
	if x != nil {
		return x.StatePayload
	}
	return nil
}

func (x *GetStateResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x06engine\x1a\fcommon.proto\"?\n" +
	"\x0fInitGameRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tplayerIDs\x18\x02 \x03(\tR\tplayerIDs\",\n" +
	"\x10InitGameResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x0fMakeMoveRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bplayerID\x18\x02 \x01(\tR\bplayerID\x12 \n" +
	"\vmovePayload\x18\x03 \x01(\fR\vmovePayload\"\x82\x01\n" +
	"\x10MakeMoveResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bgameOver\x18\x03 \x01(\bR\bgameOver\x12\"\n" +
	"\fnextPlayerID\x18\x04 \x01(\tR\fnextPlayerID\"=\n" +
	"\x0fGetStateRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bplayerID\x18\x02 \x01(\tR\bplayerID\"P\n" +
	"\x10GetStateResponse\x12\"\n" +
	"\fstatePayload\x18\x01 \x01(\fR\fstatePayload\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion2\xe8\x02\n" +
	"\rEngineService\x12=\n" +
	"\bInitGame\x12\x17.engine.InitGameRequest\x1a\x18.engine.InitGameResponse\x12=\n" +
	"\bMakeMove\x12\x17.engine.MakeMoveRequest\x1a\x18.engine.MakeMoveResponse\x12=\n" +
	"\bGetState\x12\x17.engine.GetStateRequest\x1a\x18.engine.GetStateResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponse\x12R\n" +
	"\x0fRegisterService\x12\x1e.common.RegisterServiceRequest\x1a\x1f.common.RegisterServiceResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_engine_proto_goTypes = []any{
	(*InitGameRequest)(nil),         // 0: engine.InitGameRequest
	(*InitGameResponse)(nil),        // 1: engine.InitGameResponse
	(*MakeMoveRequest)(nil),         // 2: engine.MakeMoveRequest
	(*MakeMoveResponse)(nil),        // 3: engine.MakeMoveResponse
	(*GetStateRequest)(nil),         // 4: engine.GetStateRequest
	(*GetStateResponse)(nil),        // 5: engine.GetStateResponse
	(*HealthCheckRequest)(nil),      // 6: common.HealthCheckRequest
	(*RegisterServiceRequest)(nil),  // 7: common.RegisterServiceRequest
	(*HealthCheckResponse)(nil),     // 8: common.HealthCheckResponse
	(*RegisterServiceResponse)(nil), // 9: common.RegisterServiceResponse
}
var file_engine_proto_depIdxs = []int32{
	0, // 0: engine.EngineService.InitGame:input_type -> engine.InitGameRequest
	2, // 1: engine.EngineService.MakeMove:input_type -> engine.MakeMoveRequest
	4, // 2: engine.EngineService.GetState:input_type -> engine.GetStateRequest
	6, // 3: engine.EngineService.HealthCheck:input_type -> common.HealthCheckRequest
	7, // 4: engine.EngineService.RegisterService:input_type -> common.RegisterServiceRequest
	1, // 5: engine.EngineService.InitGame:output_type -> engine.InitGameResponse
	3, // 6: engine.EngineService.MakeMove:output_type -> engine.MakeMoveResponse
	5, // 7: engine.EngineService.GetState:output_type -> engine.GetStateResponse
	8, // 8: engine.EngineService.HealthCheck:output_type -> common.HealthCheckResponse
	9, // 9: engine.EngineService.RegisterService:output_type -> common.RegisterServiceResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
