// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostID        string                 `protobuf:"bytes,1,opt,name=hostID,proto3" json:"hostID,omitempty"` // From UMS
	GameMode      string                 `protobuf:"bytes,2,opt,name=gameMode,proto3" json:"gameMode,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetHostID() string {
	if x != nil {
		return x.HostID
	}
	return ""
}

func (x *CreateGameRequest) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *CreateGameRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"` // Validated via TMS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGameRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *JoinGameRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *StartGameRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type EndGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	WinnerUserID  string                 `protobuf:"bytes,2,opt,name=winnerUserID,proto3" json:"winnerUserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndGameRequest) Reset() {
	*x = EndGameRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameRequest) ProtoMessage() {}

func (x *EndGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameRequest.ProtoReflect.Descriptor instead.
func (*EndGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *EndGameRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EndGameRequest) GetWinnerUserID() string {
	if x != nil {
		return x.WinnerUserID
	}
	return ""
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameStateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending, active, finished
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateResponse) Reset() {
	*x = GameStateResponse{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateResponse) ProtoMessage() {}

func (x *GameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateResponse.ProtoReflect.Descriptor instead.
func (*GameStateResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameStateResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GameStateResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\x1a\fcommon.proto\"g\n" +
	"\x11CreateGameRequest\x12\x16\n" +
	"\x06hostID\x18\x01 \x01(\tR\x06hostID\x12\x1a\n" +
	"\bgameMode\x18\x02 \x01(\tR\bgameMode\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x03 \x01(\x05R\n" +
	"maxPlayers\"9\n" +
	"\x0fJoinGameRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"\"\n" +
	"\x10StartGameRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"D\n" +
	"\x0eEndGameRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fwinnerUserID\x18\x02 \x01(\tR\fwinnerUserID\"%\n" +
	"\x13GetGameStateRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"P\n" +
	"\fGameResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"e\n" +
	"\x11GameStateResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12(\n" +
	"\aplayers\x18\x02 \x03(\v2\x0e.common.PlayerR\aplayers\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xcd\x03\n" +
	"\vGameService\x129\n" +
	"\n" +
	"CreateGame\x12\x17.game.CreateGameRequest\x1a\x12.game.GameResponse\x125\n" +
	"\bJoinGame\x12\x15.game.JoinGameRequest\x1a\x12.game.GameResponse\x127\n" +
	"\tStartGame\x12\x16.game.StartGameRequest\x1a\x12.game.GameResponse\x123\n" +
	"\aEndGame\x12\x14.game.EndGameRequest\x1a\x12.game.GameResponse\x12B\n" +
	"\fGetGameState\x12\x19.game.GetGameStateRequest\x1a\x17.game.GameStateResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponse\x12R\n" +
	"\x0fRegisterService\x12\x1e.common.RegisterServiceRequest\x1a\x1f.common.RegisterServiceResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_proto_goTypes = []any{
	(*CreateGameRequest)(nil),       // 0: game.CreateGameRequest
	(*JoinGameRequest)(nil),         // 1: game.JoinGameRequest
	(*StartGameRequest)(nil),        // 2: game.StartGameRequest
	(*EndGameRequest)(nil),          // 3: game.EndGameRequest
	(*GetGameStateRequest)(nil),     // 4: game.GetGameStateRequest
	(*GameResponse)(nil),            // 5: game.GameResponse
	(*GameStateResponse)(nil),       // 6: game.GameStateResponse
	(*Player)(nil),                  // 7: common.Player
	(*HealthCheckRequest)(nil),      // 8: common.HealthCheckRequest
	(*RegisterServiceRequest)(nil),  // 9: common.RegisterServiceRequest
	(*HealthCheckResponse)(nil),     // 10: common.HealthCheckResponse
	(*RegisterServiceResponse)(nil), // 11: common.RegisterServiceResponse
}
var file_game_proto_depIdxs = []int32{
	7,  // 0: game.GameStateResponse.players:type_name -> common.Player
	0,  // 1: game.GameService.CreateGame:input_type -> game.CreateGameRequest
	1,  // 2: game.GameService.JoinGame:input_type -> game.JoinGameRequest
	2,  // 3: game.GameService.StartGame:input_type -> game.StartGameRequest
	3,  // 4: game.GameService.EndGame:input_type -> game.EndGameRequest
	4,  // 5: game.GameService.GetGameState:input_type -> game.GetGameStateRequest
	8,  // 6: game.GameService.HealthCheck:input_type -> common.HealthCheckRequest
	9,  // 7: game.GameService.RegisterService:input_type -> common.RegisterServiceRequest
	5,  // 8: game.GameService.CreateGame:output_type -> game.GameResponse
	5,  // 9: game.GameService.JoinGame:output_type -> game.GameResponse
	5,  // 10: game.GameService.StartGame:output_type -> game.GameResponse
	5,  // 11: game.GameService.EndGame:output_type -> game.GameResponse
	6,  // 12: game.GameService.GetGameState:output_type -> game.GameStateResponse
	10, // 13: game.GameService.HealthCheck:output_type -> common.HealthCheckResponse
	11, // 14: game.GameService.RegisterService:output_type -> common.RegisterServiceResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
