// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: smtp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	GamerTag      string                 `protobuf:"bytes,2,opt,name=gamer_tag,json=gamerTag,proto3" json:"gamer_tag,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_smtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_smtp_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailRequest) GetGamerTag() string {
	if x != nil {
		return x.GamerTag
	}
	return ""
}

func (x *SendEmailRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SendEmailRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_smtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_smtp_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_smtp_proto protoreflect.FileDescriptor

const file_smtp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"smtp.proto\x12\x04user\"z\n" +
	"\x10SendEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tgamer_tag\x18\x02 \x01(\tR\bgamerTag\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\"?\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2K\n" +
	"\vSMTPService\x12<\n" +
	"\tSendEmail\x12\x16.user.SendEmailRequest\x1a\x17.user.SendEmailResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_smtp_proto_rawDescOnce sync.Once
	file_smtp_proto_rawDescData []byte
)

func file_smtp_proto_rawDescGZIP() []byte {
	file_smtp_proto_rawDescOnce.Do(func() {
		file_smtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smtp_proto_rawDesc), len(file_smtp_proto_rawDesc)))
	})
	return file_smtp_proto_rawDescData
}

var file_smtp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smtp_proto_goTypes = []any{
	(*SendEmailRequest)(nil),  // 0: user.SendEmailRequest
	(*SendEmailResponse)(nil), // 1: user.SendEmailResponse
}
var file_smtp_proto_depIdxs = []int32{
	0, // 0: user.SMTPService.SendEmail:input_type -> user.SendEmailRequest
	1, // 1: user.SMTPService.SendEmail:output_type -> user.SendEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smtp_proto_init() }
func file_smtp_proto_init() {
	if File_smtp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smtp_proto_rawDesc), len(file_smtp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smtp_proto_goTypes,
		DependencyIndexes: file_smtp_proto_depIdxs,
		MessageInfos:      file_smtp_proto_msgTypes,
	}.Build()
	File_smtp_proto = out.File
	file_smtp_proto_goTypes = nil
	file_smtp_proto_depIdxs = nil
}
